name: Test then push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-docker:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mscroggs/dolfinx-with-refinement
          target: dolfinx-with-refinement

  test:
    name: Run DOLFINx tests in new Docker image
    runs-on: ubuntu-latest
    container: mscroggs/dolfinx-with-refinement

    steps:
      - name: Get DOLFINx
        uses: actions/checkout@v2
        with:
          path: ./dolfinx
          repository: FEniCS/dolfinx
          ref: mscroggs/refinement
      - name: Run DOLFINx unit tests
        run: python3 -m pytest -v -n auto dolfinx/python/test/unit

    needs: build-and-publish-docker
